# Site settings
title:          unvorhergesehen.
description:    "Seele, Spirit, Leben"
baseurl:        ""
url:            "https://unvorhergesehen.github.io"

# Author
author:
  name:         Franz-Ferdinand Lehnert
  url:
  email:        lehnert@unvorhergesehen.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
